# Generated by Django 2.1 on 2020-10-31 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('gender', models.SmallIntegerField(choices=[(0, 'male'), (1, 'female')], default=0)),
                ('school', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': '学生表',
                'verbose_name_plural': '学生表',
                'db_table': 't_student',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('gender', models.SmallIntegerField(choices=[(0, 'male'), (1, 'female')], default=0)),
                ('school', models.CharField(blank=True, max_length=30, null=True)),
                ('position', models.SmallIntegerField(choices=[(0, '辅导员'), (1, '讲师'), (2, '副教授'), (3, '教授'), (4, '院长'), (5, '书记')], default=1)),
            ],
            options={
                'verbose_name': '教师表',
                'verbose_name_plural': '教师表',
                'db_table': 't_teacher',
            },
        ),
    ]
